name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Check formatting
        run: bun run check

  # Test the action itself
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test action with basic patterns
        id: changes
        uses: ./
        with:
          include: "**/*.md,**/*.yml"
          exclude: "**/node_modules/**/*"
          list-files: json

      - name: Verify outputs
        run: |
          echo "Changed: ${{ steps.changes.outputs.changed }}"
          echo "Count: ${{ steps.changes.outputs.changes_count }}"
          echo "Files: ${{ steps.changes.outputs.changed_files }}"

      - name: Test with specific patterns
        id: specific
        uses: ./
        with:
          include: "test/**/*"
          list-files: shell

      - name: Test exclude patterns
        id: exclude
        uses: ./
        with:
          include: "**/*"
          exclude: "**/*.lock,**/node_modules/**/*"
          list-files: none

  # Test on different operating systems
  test-cross-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test action cross-platform
        id: test
        uses: ./
        with:
          include: "**/*.sh,**/*.yml"

      - name: Verify cross-platform compatibility
        run: echo "Action works on ${{ matrix.os }}"
